# Generated by Django 5.1.3 on 2024-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='potencia_fuente',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
