# Generated by Django 5.1.3 on 2025-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoEntidad', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
