# Generated by Django 5.1.3 on 2024-11-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_fuente_potencia_fuente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesador',
            name='conector',
        ),
    ]
