# Generated by Django 5.1.3 on 2025-04-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0002_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='id_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Storage.entidad'),
        ),
    ]
