# Generated by Django 5.1.3 on 2024-11-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0003_remove_procesador_conector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trys',
            fields=[
                ('id_trys', models.BigAutoField(primary_key=True, serialize=False)),
                ('resultado', models.IntegerField()),
            ],
        ),
    ]
