# Generated by Django 5.1.3 on 2025-05-08 18:30

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0004_alter_pc_id_chasis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteHistorico',
            fields=[
                ('id_historico', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_version', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.pc')),
            ],
        ),
    ]
