# Generated by Django 5.1.3 on 2025-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0006_alter_lector_desc_lector_alter_lector_tipo_lector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranura_expansion',
            name='conector_ranura',
        ),
        migrations.RemoveField(
            model_name='ranura_expansion',
            name='id_board',
        ),
        migrations.AlterField(
            model_name='ranura_expansion',
            name='id_slot',
            field=models.CharField(max_length=50),
        ),
    ]
