# Generated by Django 5.1.3 on 2025-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0007_remove_ranura_expansion_conector_ranura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='observacion',
            field=models.CharField(max_length=250),
        ),
    ]
