# Generated by Django 5.1.3 on 2025-05-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0008_alter_incidencias_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambios', models.JSONField()),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('comentario', models.TextField(blank=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.pc')),
            ],
        ),
    ]
