# Generated by Django 5.1.3 on 2025-05-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0009_cambiopendiente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CambioPendiente',
        ),
    ]
