# Generated by Django 5.1.3 on 2025-05-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0010_delete_cambiopendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendienteActualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pendiente', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.JSONField()),
                ('datos_actuales', models.JSONField()),
                ('datos_nuevos', models.JSONField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('id_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.pc')),
            ],
        ),
    ]
