# Generated by Django 5.1.3 on 2025-05-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0011_pendienteactualizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendienteActualizacion',
        ),
    ]
