# Generated by Django 5.1.3 on 2025-05-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storage', '0012_delete_pendienteactualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendienteActualizacion',
            fields=[
                ('id_pendiente', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pendiente', models.DateTimeField(auto_now_add=True)),
                ('datos_nuevos', models.JSONField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('id_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storage.pc')),
            ],
        ),
    ]
